<?php

return [
    "APP_NAME" => env("APP_NAME"),

    # PayPal Gateway Config
    "PAYPAL_CLIENT_ID" => env("PAYPAL_CLIENT_ID"),
    "PAYPAL_CLIENT_SECRET" => env("PAYPAL_CLIENT_SECRET"),
    "PAYPAL_MODE" => env("PAYPAL_MODE", "sandbox"),
    "PAYPAL_CURRENCY" => env("PAYPAL_CURRENCY", "USD"),
    "PAYPAL_VERIFY_URL" => env("PAYPAL_VERIFY_URL"),
    "PAYPAL_CANCEL_URL" => env("PAYPAL_CANCEL_URL"),

    # PayTabs Gateway Config
    "PAYTABS_PROFILE_ID" => env("PAYTABS_PROFILE_ID"),
    "PAYTABS_SERVER_KEY" => env("PAYTABS_SERVER_KEY"),
    "PAYTABS_BASE_URL" => env("PAYTABS_BASE_URL"),
    "PAYTABS_CHECKOUT_LANG" => env("PAYTABS_CHECKOUT_LANG"),
    "PAYTABS_VERIFY_URL" => env("PAYTABS_VERIFY_URL"),
    "PAYTABS_CANCEL_URL" => env("PAYTABS_CANCEL_URL"),

    # Paymob Gateway Config
    "PAYMOB_API_KEY" => env("PAYMOB_API_KEY"),
    "PAYMOB_INTEGRATION_ID" => env("PAYMOB_INTEGRATION_ID"),
    "PAYMOB_IFRAME_ID" => env("PAYMOB_IFRAME_ID"),
    "PAYMOB_HMAC_SECRET" => env("PAYMOB_HMAC_SECRET"),
    "PAYMOB_CURRENCY" => env("PAYMOB_CURRENCY", "EGP"),
];
